INSERT INTO Companies (Company_name, Airplane_type)
VALUES
    ('Аэрофлот', 'Boeing 737'),
    ('S7 Airlines', 'Airbus A320'),
    ('Delta Air Lines', 'Boeing 747'),
    ('Air France', 'Airbus A330'),
    ('Japan Airlines', 'Boeing 777'),
    ('British Airways', 'Airbus A380'),
    ('Lufthansa', 'Boeing 787'),
    ('Alitalia', 'Airbus A350'),
    ('Air China', 'Boeing 737 Max'),
    ('Emirates', 'Airbus A380'),
    ('Qantas', 'Boeing 747'),
    ('Air Canada', 'Airbus A320neo'),
    ('China Eastern Airlines', 'Boeing 767'),
    ('Singapore Airlines', 'Airbus A350'),
    ('Cathay Pacific', 'Boeing 777'),
    ('All Nippon Airways', 'Airbus A320'),
    ('Korean Air', 'Boeing 737'),
    ('Turkish Airlines', 'Airbus A330'),
    ('Etihad Airways', 'Boeing 777'),
    ('Saudi Arabian Airlines', 'Airbus A320');
